export const productImages={
    product1: require('./Assets/p1.png'),
    product2: require('./Assets/p2.png'),
    product3: require('./Assets/p3.png'),
    product4: require('./Assets/p4.png'),
    product5: require('./Assets/p5.png'),
    product6: require('./Assets/p6.png'),
    product7: require('./Assets/p7.png'),
    product8: require('./Assets/p8.png'),
    product9: require('./Assets/p9.png'),
    product10: require('./Assets/p10.png'),
    product11: require('./Assets/p11.png'),
    product12: require('./Assets/p12.png'),
    product13: require('./Assets/p13.png'),
    product14: require('./Assets/p14.png'),
    product15: require('./Assets/p15.png'),
    product16: require('./Assets/p16.png'),
    product17: require('./Assets/p17.png'),
    product18: require('./Assets/p18.png'),
    product19: require('./Assets/p19.png'),
    product20: require('./Assets/p20.png'),
}